# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Properties
version:      0.60
version_from: Properties.pm
installdirs:  site
requires:
    File::Temp:                    0
    Test::More:                    0
    Text::Wrap:                    2001.0929

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
