--- #YAML:1.0
name:                Config-Properties
version:             1.70
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Temp:                    0
    Test::More:                    0
    Text::Wrap:                    2001.0929
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
